<?xml version="1.0" encoding="utf-8"?><Database Name="Obscura" Class="ObscuraLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mathis;Initial Catalog=Obscura;Integrated Security=True" SettingsObjectName="Obscura.Properties.Settings" SettingsPropertyName="ObscuraConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.xspLogHit" Method="xspLogHit">
    <Parameter Name="entityid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetEntity" Method="xspGetEntity">
    <Parameter Name="entityid" Type="System.Int32" DbType="Int" />
    <Parameter Name="TypeId" Parameter="typeId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Parameter Name="Hits" Parameter="hits" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="CreatedOn" Parameter="createdOn" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="ModifiedOn" Parameter="modifiedOn" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspUpdateEntity" Method="xspUpdateEntity">
    <Parameter Name="entityid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="typeid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetPhoto" Method="xspGetPhoto">
    <Parameter Name="entityid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="photoid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="thumbnailid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="imageid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <ElementType Name="xspGetPhotoResult">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="path" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="resolutionX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="resolutionY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspUpdatePhoto" Method="xspUpdatePhoto">
    <Parameter Name="entityid" Type="System.Int32" DbType="Int" />
    <Parameter Name="photoid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="thumbnailid" Type="System.Int32" DbType="Int" />
    <Parameter Name="imageid" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <ElementType Name="xspUpdatePhotoResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspWriteException" Method="xspWriteException">
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="origin" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="message" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="details" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="stacktrace" Type="System.String" DbType="Text" />
    <Parameter Name="clientip" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>